#!/bin/bash

cp ../opentee/keystorage/ca_keystorage_test.* CAs/keystorage/
cp ../opentee/keystorage/MakemoduleCA.am CAs/keystorage/Makemodule.am
cp ../opentee/keystorage/ta_key_storage.* TAs/keystorage/
cp ../opentee/keystorage/Makemodule.am TAs/keystorage/Makemodule.am
qbs debug
