#!/bin/bash

cp ./keystorage/ca_keystorage_test.* ../Open-TEE/CAs/keystorage/
cp ./keystorage/MakemoduleCA.am ../Open-TEE/CAs/keystorage/Makemodule.am
cp ./keystorage/ta_key_storage.* ../Open-TEE/TAs/ta_key_storage/
cp ./keystorage/Makemodule.am ../Open-TEE/TAs/ta_key_storage/Makemodule.am
cd ../Open-TEE/
qbs debug
qbs debug
qbs debug
cd -
